import os
import sys
import json
import pandas as pd

# allows importing modules from the src folder
sys.path.insert(0, os.path.dirname(__file__))

from data_loader import load_data, calculate_averages, regions

# ── paths ─────────────────────────────────────────────────────────────────────
root_dir = os.path.join(os.path.dirname(__file__), "..")
data_file = os.path.join(root_dir, "data", "world_data.xlsx")
output_file = os.path.join(root_dir, "website", "data.js")


# builds the {x, y, n} points used by each chart, for one region
def build_points(df_countries):
    h1, h2, h3 = [], [], []

    for _, row in df_countries.iterrows():
        name = row["Country Name"]

        if pd.notna(row["investment_avg"]) and pd.notna(row["gdp_latest"]):
            h1.append({"x": round(row["investment_avg"], 2), "y": round(row["gdp_latest"], 2), "n": name})

        if pd.notna(row["gdp_1990"]) and pd.notna(row["gdp_growth_avg"]):
            h2.append({"x": round(row["gdp_1990"], 2), "y": round(row["gdp_growth_avg"], 2), "n": name})

        if pd.notna(row["pop_growth_avg"]) and pd.notna(row["gdp_latest"]):
            h3.append({"x": round(row["pop_growth_avg"], 2), "y": round(row["gdp_latest"], 2), "n": name})

    return {"h1": h1, "h2": h2, "h3": h3}


def main():
    df_long = load_data(data_file)

    data = {}
    for region, slug in regions.items():
        df_countries = calculate_averages(df_long, region)
        data[slug] = build_points(df_countries)
        print(f"{region}: {len(df_countries)} countries")

    with open(output_file, "w") as f:
        f.write("// auto-generated by src/export_web_data.py -- do not edit by hand\n")
        f.write("const CHART_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")

    print(f"\nWrote {output_file}")


if __name__ == "__main__":
    main()
